name: integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "**"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: pre-commit
        uses: Foxon-Consulting/github-actions/integration/common/pre-commit@main

  # integration:
  #   uses: Foxon-Consulting/github-actions/.github/workflows/python_integration.yml@main
  #   with:
  #     python_version: "3.11"

  # releasing:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - pre-commit
  #     - integration
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: releasing
  #       uses: Foxon-Consulting/github-actions/delivery/common/release-please@main

  # delivery:
  #   needs:
  #     - releasing
  #   if: github.ref == 'refs/heads/main'
  #   permissions:
  #     contents: write
  #     pull-requests: write
   #   uses: Foxon-Consulting/github-actions/.github/workflows/python_delivery.yml@main

  build:
    # needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install build dependencies
        run: |
          pip install build
      - name: build wheel
        run: |
          python -m build --wheel
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: /tmp/${{ inputs.artifact-name }}.tar

  delivery:
    needs:
      - releasing
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path:

      - name: delivery
        run: |
          # Install Twine
          pip install twine

          # Upload the artifact to the AWS private PyPI repository
          twine upload




  deployment:
    needs:
      - releasing
      - delivery
    if: github.ref == 'refs/heads/dev'
    permissions:
      contents: write
      pull-requests: write
      uses: Foxon-Consulting/github-actions/.github/workflows/python_deployment.yml@main
